language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

os:
  - linux

addons:
  sauce_connect: true

cache:
  directories:
    - $HOME/.cache/pip
    - node_modules

sudo: false

install:
  - "pip install 'argparse>=1.2.1' --allow-all-external"
  - pip install boto 'certauth<1.2'
  - pip install git+https://github.com/esnme/ultrajson.git
  - python setup.py -q install
  - pip install coverage pytest-cov coveralls
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - python setup.py test
  - cd karma-tests && make test

after_success:
    coveralls
