language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

os:
  - linux

addons:
  sauce_connect: true

cache:
  directories:
    - $HOME/.cache/pip
    - node_modules

sudo: false

install:
  #- pip install boto certauth youtube-dl
  #- pip install git+https://github.com/esnme/ultrajson.git
  - python setup.py -q install
  - pip install -r extra_requirements.txt
  - pip install coverage pytest-cov coveralls
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - python setup.py test
  - cd karma-tests && make test

after_success:
    coveralls
