language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

dist: xenial
sudo: required

before_install:
  - ./.travis/beforeInstall.sh

install:
  - ./.travis/install.sh

script:
  - ./.travis/test.sh

after_success:
  - codecov

env:
  - WR_TEST=no WOMBAT_TEST=no

jobs:
  allow_failures:
    - env:
       - WR_TEST=yes WOMBAT_TEST=no
  include:
    - stage: test
      name: "Replay Tests"
      python: "3.7"
      env:
       - WR_TEST=yes WOMBAT_TEST=no
      addons:
        apt:
          update: true
          sources:
            - sourceline: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
              key_url: https://dl-ssl.google.com/linux/linux_signing_key.pub
          packages:
            - google-chrome-unstable  # this is canary or dev
      services: xvfb

    - stage: test
      name: "Wombat Tests"
      language: node_js
      node_js: 12.4.0
      env:
       - WR_TEST=no WOMBAT_TEST=yes
      addons:
        apt:
          update: true
          sources:
            - sourceline: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
              key_url: https://dl-ssl.google.com/linux/linux_signing_key.pub
          packages:
            - google-chrome-unstable  # this is canary or dev
      services: xvfb
