language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

dist: xenial

addons:
  chrome: stable
  firefox: latest
  sauce_connect: true

env:
  - WR_TEST=no
  - WR_TEST=yes


cache:
  directories:
    - node_modules

sudo: required

install:
  - ./.travis/install.sh

before_install:
  - "sysctl kernel.unprivileged_userns_clone=1"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - ./.travis/test.sh

after_success:
  - codecov

matrix:
  exclude:
    - env: WR_TEST=yes
      python: "2.7"
    - env: WR_TEST=yes
      python: "3.5"

