language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

os:
  - linux

addons:
  sauce_connect: true
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

env:
  - WR_TEST=no
  - WR_TEST=yes


cache:
  directories:
    - $HOME/.cache/pip
    - node_modules

sudo: true

install:
  - ./.travis/install.sh

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ./.travis/test.sh

after_success:
  - codecov

matrix:
  exclude:
    - env: WR_TEST=yes
      python: "2.7"
    - env: WR_TEST=yes
      python: "3.5"

