environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C obvci_appveyor_python_build_env.cmd"

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:        
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install --disable-pip-version-check --user --upgrade pip"
  - "pip install -U setuptools"
  - "pip install coverage pytest-cov coveralls"
  - "pip install cffi"
  - "pip install pyopenssl"
  - "pip install certauth boto3 youtube-dl pysocks"
  - "pip install codecov"

build_script:
  - "python setup.py install"

test_script:
  - "python setup.py test"

after_test:
  - rm -rf tests/coverages
  - if not exist dist mkdir dist
  - if exist .coverage (cp .coverage dist\) else (echo no .coverage)
  - codecov
  - if exist coverage.xml (cp coverage.xml dist\) else (echo no coverage.xml)

