version: '2'

services:
    proxy:
        build: ./proxy/
        links:
            - webagg:webagg

        environment:
            - "WEBAGG=http://webrecplatform_webagg_1:8080"

        ports:
            - 9080:9080

        volumes:
            - ${HOME}/.mitmproxy/:/root/.mitmproxy/

    webagg:
        build: ./webagg/
